resources:
  - name: app_{{gitBranch}}_repo
    type: GitRepo
    configuration:
      gitProvider: my_github3       
      path: SaarMJFrogCloudOps/Academy 
      branches:
        include: ^{{gitBranch}}$
      buildOn:
        commit: true

  - name: webapp_{{gitBranch}}_image
    type: Image
    configuration:
      registry: saartifactory 
      sourceRepository: docker-local
      imageName: saar-docker.jfrog.io/webapp-{{gitBranch}} 
      imageTag: latest
      autoPull: true
      
  - name: app_{{gitBranch}}_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: saartifactory
      buildName: app_{{gitBranch}}_build
      buildNumber: 1   

  - name: scanned_app_{{gitBranch}}_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: saartifactory
      buildName: scanned_app_{{gitBranch}}_build
      buildNumber: 1 

  - name: app_{{gitBranch}}_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: saartifactory
      buildName: app_{{gitBranch}}_build
      buildNumber: 1
    
  - name: app_{{gitBranch}}_helm_chart
    type: HelmChart
    configuration:
      sourceArtifactory: saartifactory 
      repository: helm-local
      chart: app
      version: "0.1.6"   

pipelines:
  - name: pipeline_app_{{gitBranch}}
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: app_{{gitBranch}}_group
          dockerFileLocation: Application/
          dockerFileName: Dockerfile
          dockerImageName: saar-docker.jfrog.io/webapp-{{gitBranch}} 
          dockerImageTag: ${run_number}
          inputResources:
            - name: app_{{gitBranch}}_repo
          integrations:
            - name: saartifactory 

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: app_{{gitBranch}}_group
          targetRepository: docker-local
          integrations:
            - name: saartifactory  
          inputSteps:
            - name: docker_build
          outputResources:
            - name: webapp_{{gitBranch}}_image

      - name: publish_app_{{gitBranch}}_build
        type: PublishBuildInfo
        configuration:
          affinityGroup: app_{{gitBranch}}_group
          inputSteps:
            - name: docker_push
          outputResources:
            - name: app_{{gitBranch}}_build_info

      - name: scan
        type: XrayScan
        configuration:
          affinityGroup: app_{{gitBranch}}_group
          failOnScan: false
          inputResources:
            - name: app_{{gitBranch}}_build_info
              trigger: false
          outputResources:
            - name: scanned_app_{{gitBranch}}_build_info

      - name: promote_app_{{gitBranch}}_build
        type: PromoteBuild
        configuration:
          affinityGroup: app_{{gitBranch}}_group
          targetRepository: docker-local
          integrations:
            - name: saartifactory
          inputResources:
            - name: app_{{gitBranch}}_build_info
          outputResources:
            - name: app_{{gitBranch}}_promoted_build_info
        execution:
          onStart:
            - set -x
      
      - name: app_{{gitBranch}}_helm_publish_main
        type: HelmPublish
        configuration:
          affinityGroup: app_{{gitBranch}}_group
          helmVersion: 3
          chartPath: Application/app         
          inputResources:
            - name: app_{{gitBranch}}_repo
          outputResources:
            - name: app_{{gitBranch}}_helm_chart
        execution:
          onStart:
            - export HELM_VERSION="3.4.1"
            - set -x
            - curl -LO "https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz"
            - mkdir -p "/usr/local/helm-v$HELM_VERSION"
            - tar -xzf "helm-v$HELM_VERSION-linux-amd64.tar.gz" -C "/usr/local/helm-v$HELM_VERSION"
            - ln -sf "/usr/local/helm-v$HELM_VERSION/linux-amd64/helm" /usr/local/bin/helm 
            - ln -sf "/usr/local/helm-v$HELM_VERSION/linux-amd64/helm" /usr/local/bin/helm3
            - rm -f "helm-v$HELM_VERSION-linux-amd64.tar.gz"
      
      - name: app_{{gitBranch}}_helm_deploy
        type: HelmDeploy
        configuration:
          affinityGroup: app_{{gitBranch}}_group
          helmVersion: 3 
          flags: --namespace {{gitBranch}} --set image.tag="$IMAGE_TAG_FLAG" --set "$REPOSITORY_FLAG"
          releaseName: app-{{gitBranch}}
          valueFilePaths: 
            - Application/app/values.yaml
          integrations:
            - name: gce 
            - name: gke
          inputResources:
            - name: app_{{gitBranch}}_helm_chart
            - name: webapp_{{gitBranch}}_image
        execution:
          onStart:
            - set -x
            - pushd $res_{{gitBranch}}_resourcePath
            - ./helminit.sh
            - popd
            - export gitBranchName={{gitBranch}}
            - echo "Recived branch name $gitBranchName"
            - export REPOSITORY_FLAG="Values.image.repository=saar-docker.jfrog.io/webapp-$gitBranchName"
            - echo "Computed repo name $repository"
            - export imageTagVariableName=res_webapp_{{gitBranch}}_image_imageTag
            - eval IMAGE_TAG_FLAG="image.tag=$((printenv $imageTagVariableName))"
            - printenv $imageTagVariableName
            - printenv $IMAGE_TAG_FLAG
            - echo "image tag flag is $IMAGE_TAG_FLAG"